.gitignore, kraken/lib/src/css/render_style.dart, kraken/lib/src/dom/element.dart, kraken/lib/src/dom/element_manager.dart, kraken/lib/src/launcher/controller.dart, kraken/lib/widget.dart, kraken/macos/libkraken_jsc.dylib
1. 支持 viewportWidth/viewportHeight 的修改, 并重新计算样式和 Layout
自测通过 
----
viewport size 的值仅保存在 ViewController 一处, 避免 copy, 通过 getter 方便取值
=> Feat: resize if viewport changed

kraken/example/lib/main.dart, kraken/example/macos/Runner/Base.lproj/MainMenu.xib
=> :recycle: Refactor: resize.

bridge/bindings/jsc/DOM/node.cc, bridge/bindings/jsc/DOM/node.h, bridge/include/kraken_bridge_jsc.h, integration_tests/specs/dom/nodes/node.ts, kraken/macos/libkraken_jsc.dylib
close https://github.com/openkraken/kraken/issues/101
=> feat: export ownerDocument

bridge/bindings/jsc/DOM/document.cc
=> fix: modify customevent to event

bridge/bindings/jsc/DOM/document.cc, bridge/bindings/jsc/DOM/element.cc, bridge/bindings/jsc/DOM/node.cc, bridge/include/kraken_bridge_jsc.h, integration_tests/runtime/global.ts, integration_tests/specs/dom/nodes/append-child.tsx, integration_tests/specs/dom/nodes/node.ts
=> fix: fix elements created by new operator didn't have ownerDocument.

bridge/bindings/jsc/DOM/document.cc, bridge/bindings/jsc/DOM/element.cc, bridge/bindings/jsc/DOM/node.cc, bridge/include/kraken_bridge_jsc.h, integration_tests/runtime/global.ts, integration_tests/specs/dom/nodes/append-child.tsx, integration_tests/specs/dom/nodes/node.ts
Reverts openkraken/kraken#178
集成失败了
=> Revert "fix: fix elements created by new operator didn't have ownerDocument."

bridge/bindings/jsc/DOM/custom_event.cc, bridge/bindings/jsc/DOM/event.cc, bridge/bindings/jsc/DOM/event_target.cc, bridge/bindings/jsc/DOM/gesture_event.cc, bridge/include/kraken_bridge_jsc.h, bridge/polyfill/package.json, kraken/analysis_options.yaml, kraken/example/lib/main.dart, kraken/example/macos/Flutter/GeneratedPluginRegistrant.swift, kraken/example/pubspec.yaml, kraken/lib/src/dom/event.dart, kraken/lib/src/dom/event_target.dart, kraken/lib/src/launcher/controller.dart, kraken/lib/widget.dart
Fix #242, #261
react 本身会在 body 节点上创建一个 click 方法，Kraken 中错误的判断会导致 body 上只能 add 一个 click 的监听事件，以至于无法冒泡到 body 上触发 click 事件。
=> fix: event bubble not works properly.

bridge/bindings/jsc/DOM/event.cc
Fixed https://github.com/openkraken/kraken/issues/163
=> fix: return value of Event.stopPropagation() should be undefined

kraken/example/lib/main.dart, kraken/example/macos/Flutter/GeneratedPluginRegistrant.swift, kraken/example/pubspec.yaml, kraken/lib/src/css/display.dart, kraken/lib/src/css/overflow.dart, kraken/lib/src/dom/element.dart, kraken/lib/src/dom/elements/script.dart, kraken/lib/src/dom/node.dart, kraken/lib/src/dom/text_node.dart, kraken/lib/src/rendering/flex.dart, kraken/lib/src/rendering/flow.dart, kraken/lib/src/rendering/recycler.dart
- example 内置 devtools, 更新依赖版本
- 去掉 display none 跳过逻辑, 在 perfromLayout 前面已经判断过了 none 了
- Node.parent 修改类型为 Node, 替换部分原来使用到的 parent -> parentElement
Related changes: https://github.com/openkraken/devtools/pull/7
=> :bug: Fix: make devtools works.

kraken/lib/src/launcher/launcher.dart
Fixed https://github.com/openkraken/kraken/issues/235
在应用刚启动的时候，window.physicalSize 为 Size.zero，导致页面 Layout 之后没有尺寸从而页面黑屏。
需要等待 Flutter Engine 更新 window.physicalSize 之后再加载 Kraken。
=> fix: fix kraken black screen on android and ios physical devices.

kraken/example/pubspec.yaml
devtools 中 toDisplayPortValue 参数与 kraken 0.8.1 同步修改，发生 Breaking change，需要升级大版本
=> chore: upgrade devtools version

bridge/bindings/jsc/DOM/element.cc, bridge/bindings/jsc/host_class.cc, integration_tests/specs/dom/elements/div.ts
修复 instanceof 运算符判断 HostClass::instance 是否属于 HostClass 返回为 false 的问题
=> fix: fix HostClass instanceof

integration_tests/specs/dom/events/mouseEvent.ts, kraken/lib/src/dom/event.dart, kraken/lib/src/dom/event_handler.dart, kraken/lib/src/gesture/gesture_manager.dart, kraken/lib/src/rendering/pointer.dart
=> feat: support dblclick.

kraken/lib/src/launcher/controller.dart
=> fix: location.href empty

kraken/lib/src/dom/window.dart
=> fix: fix window open not working when bundleURL not exist.

scripts/prepare_kraken_release_binary.js
=> fix: build error

bridge/polyfill/src/method-channel.ts, integration_tests/runtime/kraken.d.ts, integration_tests/specs/method-channel/method-channel.ts
- Rename `setMethodCallHandler` to `addMethodCallHandler`, as which behavior is exactly `ADD`
=> :recycle: refactor: rename set to add

kraken/lib/src/dom/element.dart, kraken/lib/src/dom/event_target.dart
=> fix: don't trigger event when element already disposed.

bridge/bindings/qjs/dom/node.cc, bridge/bindings/qjs/dom/node.h, integration_tests/specs/dom/nodes/clone-node.ts
添加 cloneNodes 针对 DocumentFragment 的支持。
=> feat: support clone documentFragment node.

bridge/bindings/qjs/dom/event_target.cc, bridge/bindings/qjs/dom/event_target.h, bridge/bindings/qjs/dom/node.cc, bridge/bindings/qjs/js_context.cc
https://github.com/openkraken/kraken/pull/851 这个 PR 有点代码缺失，导致集成测试失败。
=> revert: revert clone document-fragment node implements.

bridge/bindings/qjs/dom/elements/anchor_element.d.ts, integration_tests/specs/dom/elements/a.ts, kraken/example/pubspec.yaml, kraken/lib/src/dom/elements/a.dart
=> feat: HTMLAnchorElement add full property support.

bridge/CMakeLists.txt, scripts/tasks.js
=> fix: fix ios build

bridge/bindings/qjs/js_context.h, bridge/include/kraken_foundation.h, bridge/kraken_bridge.cc, scripts/tasks.js
Android 和 iOS 构建支持 ENABLE_ASAN=true 来开启 AddressSanitizer 构建
=> feat: enable asan mode for ios and android build

bridge/bindings/qjs/dom/comment_node.cc, bridge/bindings/qjs/dom/document.cc, bridge/bindings/qjs/dom/document_fragment.cc, bridge/bindings/qjs/dom/element.cc, bridge/bindings/qjs/dom/elements/image_element.cc, bridge/bindings/qjs/dom/event_target.cc, bridge/bindings/qjs/dom/event_target.h, bridge/bindings/qjs/dom/node.cc, bridge/bindings/qjs/dom/node.h, bridge/bindings/qjs/dom/style_declaration.cc, bridge/bindings/qjs/dom/style_declaration.h, bridge/bindings/qjs/dom/text_node.cc, bridge/bindings/qjs/js_context.h, bridge/scripts/code_generator/src/genereate_source.ts, kraken/lib/src/dom/element_manager.dart
解除 style 和 Element 之间的弱引用关系，避免 Element 提前被释放导致 style 继续访问导致 crash
=> fix: fix weak reference between style and element.

bridge/bindings/qjs/js_context.h, bridge/include/kraken_bridge.h, bridge/include/kraken_foundation.h, bridge/kraken_bridge.cc, kraken/lib/src/bridge/to_native.dart, kraken/lib/src/module/performance_timing.dart
只有在使用 npm run build:bridge:macos:profile 的情况下，dart 测才会收集性能数据
=> feat: only record profile data when profile mode enabled.

integration_tests/specs/css/css-display/sliver.ts, kraken/lib/src/rendering/sliver_list.dart
=> :bug: fix: hit test children not works.

integration_tests/specs/css/css-sizing/min-height.ts, integration_tests/specs/css/css-sizing/min-width.ts
修复 https://github.com/openkraken/kraken/pull/843 引入的 fit
=> chore: remove fit

kraken/lib/css.dart, kraken/lib/src/css/display.dart, kraken/lib/src/css/offset.dart, kraken/lib/src/css/opacity.dart, kraken/lib/src/css/transform.dart, kraken/lib/src/dom/element.dart, kraken/lib/src/rendering/box_model.dart, kraken/lib/src/rendering/flex.dart, kraken/lib/src/rendering/flow.dart
=> Revert "refactor: painting order"

kraken/lib/src/module/performance_timing.dart, kraken/lib/src/rendering/box_model.dart, kraken/lib/src/rendering/flex.dart, kraken/lib/src/rendering/flow.dart, kraken/lib/src/rendering/intrinsic.dart, kraken/lib/src/rendering/sliver_list.dart
只有在 profile 模式开启的情况下，paint 和 layout 才回记录耗时。
=> feat: disable profile timing record when disabled.

kraken/lib/src/css/transform.dart
Transform 动画不应该触发 Layout，避免动画过程中频繁 layout 影响帧率。
=> Fix: transform should avoid trigger layout.

bridge/bindings/qjs/dom/document.cc, bridge/bindings/qjs/dom/element.cc, bridge/bindings/qjs/dom/element.h, bridge/bindings/qjs/dom/element_test.cc, bridge/bindings/qjs/dom/elements/template_element.cc, bridge/bindings/qjs/dom/node.h, bridge/bindings/qjs/executing_context.cc, bridge/bindings/qjs/executing_context.h, bridge/bindings/qjs/garbage_collected.h
修复 ElementAttributes 计数引用错误
Fixed #1007
=> fix: fix element attributes incorrect reference count.

.github/workflows/bridge_compile_test.yml, bridge/CMakeLists.txt, scripts/tasks.js
=> feat: add ci test for bridge build

.github/workflows/code_linter.yml, .github/workflows/sync_to_release.yml
自动同步 main 代码到 flutter 2.2.x 分支
=> Feat/auto sync main to flutter 2.2.x release

kraken/lib/src/gesture/scroll_position_with_single_context.dart, kraken/lib/src/gesture/scrollable.dart
fix #1037 
精度问题导致, 所以特定机型(分辨率数字) 会触发此问题
=> fix: using Tolerance to handle number accuracy

.github/workflows/publish_to_dart_dev.yml, kraken/include/kraken_bridge_jsc.h, kraken/include/kraken_bridge_jsc_config.h
https://github.com/dart-lang/pub/issues/3143
dart 2.14 竟然不支持软链接，先用老版本 dart 代替
=> fix: fix dart publish

integration_tests/lib/plugin.dart
=> fix: plugin test entry overrides

bridge/bindings/qjs/executing_context.cc
https://www.freelists.org/post/quickjs-devel/quickjs-threads,3
=> fix: fix stack overflow with multiple thread.

kraken/example/ios/Podfile
=> fix: example M1 simulator

kraken/lib/src/devtools/modules/network.dart, kraken/lib/src/foundation/http_cache_object.dart, kraken/lib/src/foundation/http_client.dart, kraken/lib/src/foundation/http_client_response.dart, kraken/test/kraken_test.dart, kraken/test/src/foundation/http_client.dart, kraken/test/src/foundation/http_client_interceptor.dart
=> fix(test): mulit http header and test cases

.github/workflows/bridge_compile_test.yml, .github/workflows/code_linter.yml
Add Github action filter to reduce usage of action minutes.  
Ref: https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#
=> chore: add github action filter

integration_tests/macos/Runner/MainFlutterWindow.swift
=> feat: integration test always on top

bridge/CMakeLists.txt, bridge/bindings/qjs/bom/console.cc, bridge/bindings/qjs/html_parser.cc, bridge/foundation/logging.cc, bridge/foundation/logging.h, bridge/include/kraken_foundation.h, bridge/test/kraken_test_env.h, scripts/tasks.js
=> fix: fix logging in iOS.

.github/workflows/benchmark.yml, .github/workflows/integration_test_flutter.yml, .github/workflows/plugin_test_flutter.yml, .github/workflows/publish_to_dart_dev.yml
- CI 执行的时候传递 Flutter version 信息, 与宿主机上的 flutter 版本状态无关
=> feat: ci auto config flutter

.github/workflows/code_linter.yml
=> chore: add cppcheck

README.md
=> docs: update version scope

kraken/CHANGELOG.md, kraken/pubspec.yaml
1. Add CHANGELOG for 0.11.0
2. version mark to 0.11.0
=> 🎉 Release/0.11.0

scripts/set_up_nightly_release.js
=> fix: fix schedule release version

kraken/lib/src/devtools/modules/dom.dart
Same as https://github.com/openkraken/kraken/pull/1289
=> fix: devtool dom offset

integration_tests/specs/css/css-flow/containing-block.ts, integration_tests/specs/css/css-overflow/clip-002.ts, integration_tests/specs/css/css-overflow/clip-004.ts, integration_tests/specs/css/css-position/absolute-non.ts, integration_tests/specs/dom/events/touchEvent.ts
This PR is to loosen timeout limit for some test case, to make them pass.
=> test: make test pass

kraken/lib/src/dom/elements/text_form_control.dart, kraken/lib/src/widget/text_control.dart
修复 text control element 在 flutter 2.8 上 toolbar 上的操作键不响应。
=> fix: text control toolbar action fail on flutter 2.8

integration_tests/specs/css/css-overflow/clip-002.ts, integration_tests/specs/dom/elements/input.ts, integration_tests/specs/dom/elements/textarea.ts
=> test: close some tests

bridge/bindings/qjs/executing_context.cc
=> fix: error report twice

kraken/lib/src/widget/widget_to_element_adaptor.dart
修改 ElementWidget 的 properties 为 attributes，目前是 attributes 传递到 build ，对其标准的概念，以免产生歧义。
website同步修改： https://github.com/openkraken/website/pull/218
=> :art: chore: modify properties to attributes.

performance_tests/lib/main.dart
- 修复 performance test 目录下的 dart analysis 问题
=> fix: performance test dart analysis problems

bridge/CMakeLists.txt
=> quickjs文件遗漏

README.md
=>  doc: modify README.

README.md
新的 TSC 成员已经成立。
https://github.com/openkraken/TSC
=> chore: remove invitations

kraken/lib/src/css/overflow.dart, kraken/lib/src/gesture/scroll_position.dart, kraken/lib/src/gesture/scroll_position_with_single_context.dart, kraken/lib/src/gesture/scrollable.dart, kraken/lib/src/rendering/sliver_list.dart, kraken/lib/src/rendering/text_control.dart
close #1437  #1435 
实现鼠标滚轮滚动
https://user-images.githubusercontent.com/24218764/176726075-3c56c028-636b-4144-a973-96d3d3adc0e7.mov
=> feat: support scroll on overflow、input、textarea、sliver by mouse wheel to #1437
