openkraken/kraken

kraken/lib/src/launcher/controller.dart, kraken/lib/widget.dart
Closes https://github.com/openkraken/kraken/issues/85  
修复 widget resize 时 element size 未 change：
1. viewportSize change 时 body element 的 style 未更新
2. element tree 向下递归对 element 重新设置 style 时未包含 body
3. 给 element 设置 style 时不一定会触发 markNeedsLayout（如 style 中只有 backgroundColor)，需要手动 markNeedsLayout
=> fix: element size not change when widget size change

README.md, bridge/CMakeLists.txt, scripts/build_android_so.js, scripts/prepare_kraken_release_binary.js, scripts/tasks.js
1. 修复构建脚本，让 Windows 用户可以在本地构建编译 kraken 到 Android 设备上运行。
=> Fix: windows platform support build target to Android.

kraken/lib/src/dom/event_handler.dart, kraken/lib/src/launcher/controller.dart
=> fix: fix navigation failed of anchor element.

kraken/lib/src/module/navigation.dart
1. 修复 url 取参错误导致 location.href 跳转闪退，并加类型判断
2. 兼容当前路由是本地注册的情况，否则取不到 sourceUrl 会导致报错
已验证 location.href 以下四种场景的跳转：
1. url → assets
2. url → url
3. assets → url
4. assets → assets
=> fix: Fix the crash caused by navigation in dart

kraken/pubspec.yaml
现象：device_info 目前版本太低，导致 kraken 集成到业务侧会遇到依赖冲突。
解决方案：升级 device_info 至 1.0.0。
注意：已验证接口上 1.0.0 与目前 0.4.1 是对齐的，直接升级即可。暂无法升级到 2.0.0，因其需要 Flutter 2.x，而 Kraken 对于 Flutter 2.x 还未完全适配。
=> chore: update device_info, fix #260

bridge/CMakeLists.txt, scripts/tasks.js
添加一些必要的脚本，用来支持和一个 debug 版本进行编译构建。
除了这些脚本之外，能够运行之前还需要以下三个步骤 （macOS 系统）：
1. 去这里下载 debug 版本的 jsc  https://github.com/openkraken/jsc/releases
2. 在 pubspec.yaml 里面添加 jsc 的依赖 （通常在 `~/.pub-cache/hosted/` 目录下）
3. 将下载的 debug 版本的 jsc 打包成 zip，然后替换掉 `jsc/macos` 中的 JavaScriptCore.framework.zip
4. 使用 `node scripts/build_darwin_dylib.js --built-with-debug-jsc` 重新构建 bridge
5. flutter run
=> feat: add scripts for debuggable jsc.

integration_tests/specs/method-channel/method-channel.ts, kraken/lib/src/launcher/controller.dart, kraken/lib/src/module/method_channel.dart
Fixed #287
在之前的实现中，由于 Dart 向 JS 侧发送消息的回调函数会在 MethodChannel module 初始化的时候绑定，而 module 的设计是只有调用方法的时候才进行初始化，这就导致了在 MethodChannelModule 在初始化之前，都无法调用 JS 侧的方法。
将回调函数的绑定移动到 KrakenController 初始化阶段即可解决这个问题。
=> fix: fix kraken.methodChannel.setMethodCallHandler did't get called before kraken.invokeMethod called.

bridge/bindings/jsc/DOM/element.cc, bridge/bindings/jsc/DOM/elements/input_element.cc
Kraken 中很多代码针对需要 flushUICommand 的场景，都已经做了特殊处理，因此不需要在一些通用的链路添加这个调用，会影响通道的传输性能
=> fix: remove unnecessary flushUICommand

bridge/bindings/jsc/DOM/document.cc, integration_tests/specs/dom/events/mouseEvent.ts
1. bridge 注册 cancel 事件：handleMouseEvent 传 cancel 事件时会导致 crash，使用 touchend 时真机更容易复现 #307
2. 增加 touch event 测试用例
=> fix: touchend crash caused by bridge #307

bridge/CMakeLists.txt, bridge/bindings/jsc/DOM/elements/svg_element.cc, bridge/bindings/jsc/DOM/elements/svg_element.h, bridge/bridge_jsc.cc
支持一个 SVGElement 的方法，否则最新 Vue 项目会判断节点是否是 SVGElement 而导致报错。
close #336
=> feat: add SVGElement

bridge/bindings/jsc/DOM/element.cc, integration_tests/specs/dom/nodes/element.ts
读取 Element 属性之前，需要先 flushUICommand 创建 Element。
这是这个性能优化引发的一个 Bug，https://github.com/openkraken/kraken/pulls?q=is%3Apr+is%3Aclosed
经检查，其他类似的情况都添加了 flushUICommand 的调用
=> fix: fix bridge with getStringProperty on InputElement.

bridge/bindings/jsc/DOM/element.cc, bridge/bindings/jsc/DOM/style_declaration.cc
存储在 StyleDeclaration 和 ElementAttributes 中的值需要保留引用，以免被 GC 回收导致 bad access。
=> fix: should protect StyleDeclaration and attribute valueRef.

README.md, scripts/tasks.js
社区反馈 android 版本的 bridge 无法构建， 使用 21.4.7075529 版本的 NDK 可以正常进行构建。
=> chore: fixed ndk version.

integration_tests/lib/bridge/from_native.dart, sdk/pubspec.yaml
1. chars 非空, 不需要再判断了
2. sdk 的 pubspec.yml 有一个 dart analysis 的规则 lint, 绕一下
=> :ambulance: hotfix: solve dart analysis problems.

kraken/lib/src/launcher/launcher.dart
通过判断 `window.physicalSize` 是否为空来确认是否需要监听 window.onMetricsChanged 事件来启动 kraken
=> fix: fix launcher empty screen.

bridge/bindings/jsc/DOM/event_target.cc, bridge/include/kraken_bridge_jsc.h, integration_tests/specs/dom/events/property_event.ts
修复执行 `element.onclick = null` 而抛出 JS 异常的问题，并且添加对应的实现。
=> fix: fix property event handlers when setting null value to property.

bridge/include/kraken_bridge.h, bridge/kraken_bridge.cc, kraken/example/assets/bundle.js, kraken/lib/src/bridge/to_native.dart, kraken/lib/src/launcher/controller.dart
修复页面刷新的过程中，指令执行顺序错误的问题
Fixed #118
=> fix: fix kraken page reload.

kraken/lib/src/dom/elements/input.dart
fix https://github.com/openkraken/kraken/issues/430  
节点销毁的时候, renderEditable 会被置为 null, 这里的异步操作需要判空, 如果已经销毁就不再需要执行
=> :bug: fix: input render editable can be destroyed.

integration_tests/specs/dom/elements/input.ts, kraken/lib/src/dom/element_native_methods.dart, kraken/lib/src/dom/elements/input.dart
Close https://github.com/openkraken/kraken/issues/2
=> feat: <input> support inputmode

kraken/lib/src/foundation/http_client_interceptor.dart
返回 null 表示不进行网络拦截, 抽象类的之前迁移的时候没有加对 nullable
=> :bug: fix: HttpClientInterceptor should accept nullable

bridge/kraken_bridge.cc
修复创建JSBridge时返回错误的contextId的问题
=> fix: allocate new context error

bridge/kraken_bridge.cc
修复一个问题：
1.JSContext被覆盖，contextPool[0]被重复赋值。
复现步骤：首次启动，打开一个kraken页面，contextPool[0]会被赋值，在当前kraken页面再打开一个kraken页面，此时contextPool[0]又会被赋一次值。
=> fix: correct context pool index

bridge/kraken_bridge.cc
disposeAllBridge方法里面使用的小于等于poolIndex，而poolIndex可能会大于maxPoolSize。
复现步骤：连续打开关闭kraken页面，使得poolIndex大于等于maxPoolSize，然后使用热重载或者销毁FlutterEngine再启动，再次打开kraken页面时有可能会crash。
=> fix: 修复野指针可能导致的不可预知问题

bridge/bridge_jsc.cc
由于全局热更新调用了 krakenModuleListener，如果上一个 krakenModuleListener 是 reload ，则会调用 JSContext 的析构函数销毁上下文，下一个方法访问时则会 crash。
=> fix: hotreload crash.

kraken/lib/widget.dart
Fixed #485 
提前预热 FlutterEngine 而没有创建 FlutterViewController 会导致 Kraken 读取到的 window.physicalSize 为 0， 从而无法正常渲染页面。
对于这种情况，最佳的方式就是交给用户自行处理，让用户在 Native 侧获取尺寸并传递给 kraken。
> Kraken 可以监听 window.onMetricsChanged 回调来自动进行渲染 resize，但是这样并不高效，而且 FlutterView 在进行手势动画的过程中，iOS 会修改 FlutterView 的尺寸，从而触发大量 window.onMetricsChanged 调用。
> 所以让用户自己在 native 提前获取尺寸才是最好的方式
=> fix: add exception report when viewportSize is 0

integration_tests/specs/css/css-backgrounds/linear-gradient.ts, integration_tests/specs/css/css-images/linear-gradient.ts, kraken/lib/src/css/background.dart
Closes #511 
原因：针对渐变校验计算规则错误，对于有多个右括号的校验无法命中，导致渐变无法渲染，示例
linear-gradient(to right, rgba(35, 35, 35, 0.8), rgba(35, 35, 35, 0.1))
修复：改为校验最后一个右括号作为完整校验
=> fix. gradient check wrong when has more than one right bracket

integration_tests/specs/css/css-values/rem.ts, kraken/lib/src/dom/element.dart, kraken/lib/src/dom/elements/canvas/canvas.dart, kraken/lib/src/dom/elements/canvas/canvas_context_2d.dart
* 修复 https://github.com/openkraken/kraken/pull/475 PR 中 fit 未移除导致未发现的测试失败的问题：
- 去除 test 中 fit。
- 在 renderer before attach 时不需要 apply style properties。
- canvas.dart 中取 fontSize 与 rootFontSize 时由于 renderBoxModel 未创建导致测试用例 crash，取将取 fontSize 与 rootFontSize 时机移到 didAttachRenderer。
=> fix: remove fit

kraken/lib/src/rendering/viewport.dart
Closes https://github.com/openkraken/kraken/issues/556
* 修复 Kraken widget size 不对，不应该使用屏幕宽高，而应该使用 widget 上设置的 viewportWidth/viewportHeight。
=> fix: kraken widget size

kraken/lib/src/dom/elements/input.dart
Closes https://github.com/openkraken/kraken/issues/594
原因：键盘 enter key 按下时会触发 input 的 blur 操作，由于多 input 的存在，在 InputElement 中以静态变量形式保存了当前 focus 的 element，原逻辑 blur 时未将 focusElement 清空，导致下次选中 input 时 focusElement 与上一次相等，从而无法选中。
=> fix: input can not focus when hitting enter key

kraken/lib/src/bridge/to_native.dart, kraken/lib/src/dom/event_target.dart
修复因context被释放后继续执行js和分发事件导致的crash
=> fix: crash caused by context has been released

kraken/lib/src/dom/elements/input.dart
Closes https://github.com/openkraken/kraken/issues/625
* 修复当使用键盘上右上角的收起按钮收起键盘后，再次点击 input，键盘未调出。原因是收起键盘时 input 仍然处于 focus 状态（关于这点 android 与 ios 表现不同，android 上收起键盘 input 仍处于 focus 状态而 ios 上 input 会失焦），原逻辑只有当 input 获取焦点时才会调起键盘，应改成 input 每次状态变化（如光标位置变化）时均调起键盘。
=> fix: keyboard not shown when keyboard dismissed and input gets focused again

integration_tests/specs/dom/elements/input.ts, kraken/lib/src/dom/elements/input.dart, kraken/lib/src/dom/event.dart
Closes https://github.com/openkraken/kraken/issues/624
* 修复 input 失去焦点时且 value 有变化时，change 事件未触发。
=> fix: input change event

bridge/bindings/jsc/DOM/event_target.cc, bridge/bindings/jsc/js_context_internal.cc, bridge/bridge_jsc.cc, bridge/include/kraken_bridge_jsc.h, bridge/include/kraken_bridge_jsc_config.h, bridge/kraken_bridge.cc, bridge/polyfill/src/index.ts, integration_tests/specs/window/onerror.ts
=> Feat: support window onerror and global error event

bridge/polyfill/src/xhr.ts
xhr 去掉了相对路径判断的话，需要在 new URL 时候加入第二个参数，否则会抛异常。
close #642
=> fix: relative path of xhr.

kraken/lib/src/rendering/box_model.dart
- Solve hit test when child render object is marked as detached.
=> :bug: fix: hit test with detached child render object

kraken/lib/src/dom/elements/canvas/canvas_context_2d.dart, kraken/lib/src/dom/elements/canvas/canvas_painter.dart
- Picture 是个指令收集器, 使用 picture 作为 snapshot 实质上只是让 UI 线程(dart vm)的指令扁平化了, 但是 c++ engine 侧的指令还在累计, 通过 picture.approximateBytesUsed 可以看到数字在不断增长; 把 Picture 转换为 Image 作为 snapshot 可以解决这个问题
fix #676
=> :zap: performance: improve canvas drawing performance

bridge/CMakeLists.txt, bridge/cmake/ios.toolchain.cmake, performance_tests/pubspec.lock, scripts/tasks.js, sdk/pubspec.lock
=> fix: fix ios app store

bridge/bindings/qjs/js_context.h, bridge/include/kraken_foundation.h, bridge/kraken_bridge.cc, kraken/lib/src/foundation/http_cache.dart
We don't have native implementation of temporary directory on Windows and Linux platform.
So we temporary disable it.
=> feat: disable http cache for windows and linux

kraken/lib/src/css/overflow.dart, kraken/lib/src/dom/element.dart, kraken/lib/src/dom/event_handler.dart, kraken/lib/src/gesture/scrollable.dart, kraken/lib/src/rendering/box_model.dart, kraken/lib/src/rendering/flex.dart, kraken/lib/src/rendering/flow.dart, kraken/lib/src/rendering/sliver_list.dart
Fix memory leaks caused by scrolling, eventHandler and cached lists.
=> fix: fix renderObject and element memory leaks.

bridge/bindings/qjs/js_context.cc, bridge/bindings/qjs/js_context_test.cc
修复当一个 新的 Context 创建后，新的 Context 会覆盖原先 context 所注册的 JS_SetHostPromiseRejectionTracker 回调，导致原先 context 触发 promise 异常时找不到上下文。
=> fix: fix crash when reportError.

kraken/lib/src/rendering/intersection_observer.dart
计算 intersection observer layer 的 transform 时加缓存， layer 向上 multiply transform 时公共的 layer transform 不用重复计算，提升计算性能。
=> fix: intersection observer performance

bridge/bindings/qjs/dom/document.cc, bridge/bindings/qjs/dom/document.h, bridge/bindings/qjs/dom/document_test.cc, bridge/bindings/qjs/dom/element.cc, bridge/bindings/qjs/dom/element.h, bridge/bindings/qjs/html_parser.cc
Fixed #931
由于 Element 构造函数没有按照 JSContext 进行分离，所以存在其中一个页面销毁的同时，销毁所有 Context 共享的公共构造函数。
修复方案：每个 Context 都有独立的 Element 构造函数，相互之间不影响。
=> fix: fix document.createElement in multiple context

bridge/bindings/qjs/bom/window.cc, bridge/bindings/qjs/bom/window.h, bridge/bindings/qjs/dom/event_target.cc, bridge/bindings/qjs/dom/event_target.h, bridge/bindings/qjs/js_context.h
在一些特殊的条件下（例如节点被卸载）等，gc_mark 无法正确被 GC 掉用，从而导致对象内部和对象本身没有绑定的属性无法释放。
先采用 Object.defineProperty 这样的方式来绑定属性，可以确保属性 100% 可以被 GC 定位并释放
=> fix: free event targets properties by gc mark.

kraken/lib/src/rendering/intersection_observer.dart
由于 layer 的 applyTransform 有副作用，传入的 transform 会被改掉，因此 intersection observer 的 cache 在使用时需要先 clone 防止下一次使用时被修改。
=> fix: intersection observer cache

kraken/lib/src/rendering/box_model.dart
修复 parent 有可能不是 RenderBoxModel 的类型错误。
=> fix: fix markParentNeedsRelayout error.

kraken/lib/src/dom/elements/img.dart
回滚 @temper357   https://github.com/openkraken/kraken/pull/916 误删的代码。
误删的代码会导致 _renderImage 没有 width 和 height 属性， 导致 gif 每次播放都会 markNeedsLayout 从而导致剧烈卡顿。
=> fix: fix image gif image cause whole document layout.

kraken/lib/src/bridge/to_native.dart, kraken/lib/src/css/positioned.dart, kraken/lib/src/dom/element.dart, kraken/lib/src/dom/elements/img.dart, kraken/lib/src/rendering/sliver_list.dart
1. 修复 sliver 在延迟触发加载的时候，RenderViewport 的 relayoutboundary 阻挡了 RenderSliverList 触发 performLayout 导致节点未同步的问题, 同时修复这种情况下滚动监听器被覆盖的问题
2. 修复 img 的尺寸计算中宽高有可能为 resolved auto, 从而产生 infinity 的问题 cc @temper357 
3. 修复 placeholder 有可能未上树 (sliver 或者其它 widget 场景下), 计算 offset 异常的问题
4. 其它类型 cast 修复
=> fix: sliver usage and other problems

bridge/CMakeLists.txt, scripts/tasks.js
支持将 quickjs 作为静态库，直接集成在 kraken 的 bundle 里面。
支持已支持的 macOS，android，iOS 平台。
使用方法：
```
npm run build:bridge:macos:release -- --static-quickjs
```
=> feat: add option to build quickjs as static library

kraken/lib/src/rendering/box_model.dart
PR 中删除的代码会使 flex item 的 relayout boundary 失效，即使 flex item 上有设置宽高，还是会继续向上冒脏标识。
这段代码的原始含义是，flex item 的 size 变化时可能影响到 sibling 的 size，如果 flex item 自身是 relayout boundary 那么脏标识不会冒泡到 parent，重构过后的代码中这个逻辑已经在 css 属性的 setter 中处理过了，因此这段逻辑不是必需的。
=> fix: relayout boundary of flex item

bridge/bindings/qjs/dom/event_target_test.cc, bridge/bindings/qjs/executing_context.h
Fixed #1035
修复全局绑定 addEventListener 报错的问题
=> fix: fix this_val on global func call

kraken/lib/src/rendering/intrinsic.dart
Closes https://github.com/openkraken/kraken/issues/1075
* 修复图片总会创建 clipRectLayer 导致 paint 性能下降产生滚动卡顿，只当 border-radius 存在且 image load 完成时创建 layer，该 fix 可减少大部分因无 border-radius 的 image 产生的卡顿，更优的方案是 border-radius 的 image 使用 canvas.clipRect 的方案，仍在开发中，见此 PR https://github.com/openkraken/kraken/pull/1076。
=> fix: RenderIntrinsic should only clip when border-radius exist

kraken/lib/src/dom/elements/input.dart, kraken/lib/src/widget/kraken.dart
Closes https://github.com/openkraken/kraken/issues/1092
1. 在 Kraken 的 widget 中 override 系统的 action，补充 RenderEditable 在 Flutter 2.5 版本中被移除的 delete 及 hotKey 对应的 action。
2. 通过 diff Flutter 2.2 与 2.5 版本的 editable_text.dart （对应 Kraken 拷贝出来修改的 input.dart），发现一处 _selectionOverlay 相关的逻辑变更，同步到 Kraken。
=> fix: input hotkey and delete command fail due to flutter 2.5 upgrade

kraken/lib/src/bridge/from_native.dart, kraken/lib/src/dom/element.dart, kraken/lib/src/dom/node.dart, kraken/lib/src/dom/sliver_manager.dart, kraken/lib/src/dom/text_node.dart, kraken/lib/src/launcher/controller.dart
修复页面刷新，RenderViewport 的挂载问题。
Kraken 刷新页面，不会触发 Kraken 外层 Flutter Widget 树的更新。因此需要保留上一个页面 RenderViewportBox，把内部的 RenderObject 都删除，待页面刷新完成，再将新的页面内容，挂载到原先的 RenderViewportBox 下面。
缺乏测试基建，暂时无法写测试，测试基建搭建 @andycall
=> fix: fix page reload.

scripts/tasks.js
修复 linux binary rpath 路径问题。
使用相对路径可以让 libkraken.so 可以找到 libquickjs.so.
=> fix: fix linux dynamic rpath

kraken/android/CMakeLists.txt, kraken/android/build.gradle
1. Remove android integrate cmake
=> chore: remove android cmake

kraken/lib/src/painting/cached_network_image.dart
修复图片请求在关闭 HttpCache 的情况下，依然访问了 Cache
=> fix: image load disable cache if HttpCacheMode set to NO_CACHE

bridge/bindings/qjs/bom/window.cc, bridge/bindings/qjs/bom/window_test.cc, bridge/bindings/qjs/dom/element.cc, bridge/bindings/qjs/dom/event_target.cc, bridge/bindings/qjs/dom/events/message_event.d.ts, bridge/bindings/qjs/dom/frame_request_callback_collection.cc, bridge/bindings/qjs/executing_context.cc, bridge/bindings/qjs/html_parser.cc, bridge/bindings/qjs/js_context_test.cc, bridge/bindings/qjs/native_value.cc
Fixed #1099
没有释放的 Exception 会导致 globalObject 没有被释放，globalObject 没有释放会导致 GC Tracker 没有释放，GC tracker 没有释放会导致当销毁一个 ExecutionContext 时，基于 JSContext 所创建的对象并没有完全被清空，依然会残留在 GC 的队列里。
待下次执行 GC 的时候，就从没有被回收的对象访问到已经被释放的 JSContext，导致 Crash。
TODO: test
=> fix: fix exception leak cause globalObject not fully freed.

integration_tests/pubspec.yaml, kraken/lib/src/css/visibility.dart, kraken/lib/src/rendering/box_model.dart, kraken/lib/src/rendering/intrinsic.dart, kraken/lib/src/rendering/opacity.dart
Close #1097   
测试用例复用 opacity 原有用例  
opacity 的改变不会影响元素原先的 appear/disappear 行为, 故不能中止 paint, 所以与 visibility: hidden 处理不同
=> refactor: imporove opacity 0

kraken/lib/src/dom/event.dart
按照标准，Message.data 应当是 any 类型。
修复测试中，WebSocket 插件报错
=> fix: fix MessageEvent.

kraken/lib/src/foundation/http_client_request.dart, kraken/test/fixtures/GET_301, kraken/test/src/foundation/http_cache.dart
Close #978
- 修复未透传 HttpClientRequest 的 5 个可选参数的问题, 会导致如果设置了这几个参数后被忽略的问题
=> fix: request options not pass through

kraken/lib/src/foundation/http_client_request.dart, kraken/test/local_http_server.dart, kraken/test/src/foundation/http_client.dart
Fix #1171
当 data 过大的时候, 直接使用 add 接口会导致异常, 此时需要使用 addStream 分批发送数据
=> fix: large file content may fail

kraken/lib/src/dom/elements/img.dart
不正确的 Image 加载导致 assert，触发了大量 error 事件，由于 Assert 中断了后续操作导致了 Dart Element 进入未定义的状态，进而导致更多的问题。
=> fix: fix image load error cause crash.

bridge/CMakeLists.txt, bridge/bindings/qjs/bom/window_test.cc, bridge/bindings/qjs/dom/custom_event.cc, bridge/bindings/qjs/dom/custom_event.h, bridge/bindings/qjs/dom/document.cc, bridge/bindings/qjs/dom/elements/image_element.cc, bridge/bindings/qjs/dom/event.cc, bridge/bindings/qjs/dom/event.h, bridge/bindings/qjs/dom/event_target.cc, bridge/bindings/qjs/dom/events/touch_event.cc, bridge/bindings/qjs/executing_context.cc, bridge/scripts/code_generator/src/genereate_source.ts, bridge/test/kraken_test_env.cc, kraken/android/jniLibs/x86/libc++_shared.so, kraken/android/jniLibs/x86/libkraken.so, kraken/android/jniLibs/x86/libquickjs.so, scripts/tasks.js
修复 nativeEvent 在 32位机器上的内存对齐问题。
Dart 发送给 Native 的事件都是按照 64位机器的规则进行内存布局。因此需要避免在 Native 测的 NativeEvent 声明中使用指针类型，因为它会导致在 32位机器上，按照 32 位的规则来进行偏移。
=> fix: fix native event memory align on 32 bit devices.

kraken/lib/src/bridge/to_native.dart
[04chapter_002.html.zip](https://github.com/openkraken/kraken/files/8311406/04chapter_002.html.zip)
在解析这个 html 时，发现只渲染了一半，bridge 层调了看下发现 
https://github.com/openkraken/kraken/blob/main/bridge/bindings/qjs/html_parser.cc#L129
就出了问题。
尝试修改下，只测了下自带的 bundle.html ，看起来没问题，请各位 review 下
=> fix: can't fully parse html

kraken/lib/src/dom/element.dart, kraken/lib/src/dom/elements/head.dart, kraken/lib/src/launcher/bundle.dart, kraken/lib/src/launcher/controller.dart, kraken/lib/src/module/history.dart, kraken/test/kraken_test.dart, kraken/test/src/launcher/bundle.dart
- 修复 KrakenBundle 不支持 file:// 协议的问题
- 配套测试
- 移除了 NetworkAssetBundle, 这个类不是 KrakenBundle 而是 flutter/service 的 AssetBundle, 起的作用是封装 Http 请求, 理论上无必要, 且每次都新建一个 HttpClient, 本次改动改成复用同一个 HttpClient, 逻辑收敛到 NetworkBundle 类上. 
- 后续会把图片的 httpClient 与这个 httpClient 共享
=> fix: file protocol and test cases

kraken/lib/src/launcher/bundle.dart, kraken/pubspec.yaml, kraken/test/src/launcher/bundle.dart
- 修复 fromBytecode 的 content type 类型, 增加了测试用例
- 申请发布 0.10.3+1
=> hotfix: from bytecode

kraken/lib/src/foundation/bundle.dart, kraken/test/src/foundation/bundle.dart
Close #1262 
- 修复 KrakenBundle.fromString 包含中文字符异常问题
=> fix: DataBundle string with non latin

kraken/lib/src/dom/window.dart, kraken/lib/src/launcher/controller.dart, kraken/lib/src/module/navigator.dart
修复 ui.window 上的回调函数的闭包内引用 dom.window 导致 kraken 销毁时无法释放完整的 DOM 树的问题  
**修复前创建 - 销毁 Kraken 实例可以看到仍有 Kraken 相关的对象实例存在**
**修复后增量内存不含 Kraken 对象**
=> fix: memory leaks from window

bridge/dart_methods.cc, bridge/foundation/logging.cc, bridge/foundation/logging.h, bridge/include/dart_methods.h, bridge/kraken_bridge.cc, bridge/test/kraken_test_env.cc, kraken/lib/src/bridge/from_native.dart, kraken/lib/src/devtools/inspector.dart, kraken/lib/src/devtools/modules/log.dart, kraken/lib/src/devtools/server.dart, kraken/lib/src/launcher/controller.dart
=> fix: devtool console log

kraken/lib/src/dom/elements/canvas/canvas.dart, kraken/lib/src/dom/elements/canvas/canvas_context_2d.dart, kraken/lib/src/dom/elements/canvas/canvas_painter.dart
The PR is aimed to fix the white-flash of canvas painting.
The white flash appears because our canvas painter saved the prev frame snapshot into `ui.Image`, but this process is async, see `CanvasPainter.paint()`
```dart
_snapshot = await picture.toImage(size.width.toInt(), size.height.toInt());
```
If the next frame comes faster than snapshot was generated, the next group of actions is added to action list, and removed immediately after image has created, makes canvas flash.  
`CanvasPainter` keeps `_actions` and `_pendingActions`, if `performActions()` is called, mark `_actions` as `_pendingActions`, make `_actions` to the new list, clear pending actions after snapshot is created by `clearActions`.
Close #1314 
https://user-images.githubusercontent.com/3922719/162897895-6bb5f016-04f2-4708 …
=> fix: avoid canvas painting flash

bridge/foundation/logging.cc, kraken/lib/css.dart, kraken/lib/src/css/animation.dart, kraken/lib/src/css/transition.dart, kraken/lib/src/dom/document.dart
This PR is aimed to fix the memory leak from AnimationTimeline.
The original `_documentTimeline` instance is a wild global object, so if we dispose the kraken page, it always exists. Further more, the `AnimationTimeline` keeps lists of `Animation`, `Animation` keeps reference of `KeyframeEffect`, the `KeyframeEffect` keeps reference of `Element` and `RenderStyle`, making memory leaks widely!
Also, if more than one instance of kraken page created, the documentTimeline is still the common one, causing state shared by pages, that's what we don't wanna see.  
The `Document` object will keep a final member `animationTimeline`, each node can visit it by `ownerDocument.animationTimeline`. It will be dispose when document object is disposed.
=> fix: animation timeline lifecycle, to avoid memory leak.

kraken/lib/src/rendering/paragraph.dart
由于 Flutter 的 line-height 逻辑与 Web 不一致，Kraken 渲染 line-height 的逻辑是：
1. 将 text 拆分成多行，生成多行 textPainters 数组。
2. 根据 lineMetrics 生成每行 offset 的 lineOffset 数组。
3. 在 paint 时每行 textPainter 会对应每行的 lineOffset 分别进行 paint。
由于 step 1 和 step 2 并不是同一个 api 计算出来的，在某些 edge case 下可能会出现 textPainters 的 length 大于 lineOffset length 的情况，因此在 step 3 中加上保护，保证 textPainters 与 lineOffset 一一对应。
=> fix: exception in paragraph paint in some edge cases

bridge/bindings/qjs/dom/event_type_names.cc
[std::find](http://en.cppreference.com/w/cpp/algorithm/find) is defined in the <algorithm> header. Add to the beginning:
```cpp
#include <algorithm>
```
=> fix: include algorithm

kraken/lib/src/dom/elements/script.dart, kraken/lib/src/foundation/convert.dart, kraken/lib/src/launcher/controller.dart
Close #1340 
给 `resolveStringFromData` 方法增加一个参数 `preferSync`，用以指定是否尽量使用同步 decode 加快编解码的速度  
对于加载 entrypoint 来说需要尽量使用同步，以尽快展示页面，对于异步的脚本或样式可以使用异步的方式避免阻塞进程
=> refactor: make entrypoint load with sync decoding

kraken/lib/src/dom/event_target.dart
修复触发事件时产生的 concurrent 异常   
当派发事件时, 前一个监听器同步修改了监听器 list, 会导致遍历 list 过程异常
=> fix: event concurrent exception

kraken/lib/src/foundation/bundle.dart, kraken/lib/src/launcher/controller.dart, kraken/lib/src/launcher/launcher.dart
Not to treat url `https://path/to/file.html` as an HTML content, because it may be not.   
Just specified by the `content-type` headers.  
> Excluding kbc1, it's useful for most http server that did not recognize a .kbc1 file, simply treat some.kbc1 file as the bytecode format.
=> refactor: not to treat ext as content type, excluding kbc

kraken/lib/src/gesture/gesture_dispatcher.dart
一个偶现的错误，handlePointerEvent 这个函数只处理 基本的 point 事件，也就是 up、down、cancel 以及 move，其余的类似 hover 事件加入会使得 toTouch 时的 list 数据异常而导致 use a null value。
=> :bug: fix: handlePointerEvent

bridge/bindings/qjs/dom/elements/script_element.d.ts, bridge/bindings/qjs/dom/event_target.cc, integration_tests/assets/defineA.js, integration_tests/assets/defineB.js, integration_tests/specs/dom/elements/script.ts, kraken/example/assets/defineA.js, kraken/example/assets/defineB.js, kraken/lib/src/dom/elements/script.dart
修复 script 标签在使用时的异常
1. 修复 script 标签加载异常抛出 error 事件处理导致崩溃的问题
2. 修复 script 标签标记为 async 执行异常的问题, 增加了测试用例
=> fix: script async can be delayed, error event trigger without exception

bridge/bindings/qjs/dom/event_target.cc, integration_tests/specs/dom/events/event.ts, kraken/lib/src/bridge/binding.dart
1. Bridge 在调用 UICommand::addEvent 与 UICommand::remveEvent 时都应当考虑当前 EventTarget 已经没有监听器的情况
2. 在 Bridge/binding.dart 增加了 assert 帮助提早发现多次监听或重复取消监听的情况
3. 增加了测试用例
=> fix: event handlers removal with once time

kraken/lib/src/dom/document.dart, kraken/lib/src/widget/text_control.dart
- 修复 viewport 被多次 dispose 的问题
- 原因是 Document 在被 GC 时会触发其 dispose(), 在这个方法里还调用了 viewport 的 dispose()，接着在 State unmount() 中又调用了 viewport 的 dispose，导致多次触发
- 正常情况下 dispose 遵循谁创建谁销毁原则，RenderViewportBox 是 controller 创建的，但是其是 RenderObject，故又受到 Widget Framework 的控制，这里 dispose 必须是被 framework 触发
=> fix: dispose

kraken/lib/src/gesture/scrollable.dart
给Scrollable组件添加一个dragDevices列表，表示对滚动支持的事件类型，例如鼠标长按拖动不再支持列表滚动
=> fix: add PointerDeviceKind on scrollable to #1437

kraken/lib/src/dom/elements/head.dart, kraken/lib/src/launcher/controller.dart
[fix] kraken not support relative protocol
由于HistoryModule的_replaceState过程中重新构建了bundle,此bundle未resolve,导致resolvedUri为空。
=> [fix] kraken not support relative protocol 
